extends: stylelint-config-standard

plugins: [stylelint-order]

processors: [stylelint-processor-styled-components]

syntax: scss

rules:
  rule-empty-line-before: null

  # Order
  order/order: [
    custom-properties,
    declarations,
    rules
  ]
  order/properties-alphabetical-order: true
